use crate::error::Result;
use crate::protocol::FileChange;
use async_trait::async_trait;
use serde::Serialize;
use std::borrow::Cow;

/// Runtime status exposed to a paired browser.
#[derive(Debug, Clone, Serialize)]
pub struct RuntimeStatus {
    /// Whether deterministic explanation queries are supported by this adapter.
    pub explanations_available: bool,
    /// Displayed workspace root, never a secret.
    pub workspace_root: String,
    /// Whether the bridge has a connected runtime adapter.
    pub connected: bool,
    /// Whether the adapter can submit prompts to an agent runtime.
    pub turns_available: bool,
    /// Whether mutation requests can be authorized by the runtime.
    pub mutations_allowed: bool,
    /// Whether check requests can be authorized by the runtime.
    pub checks_allowed: bool,
    /// Human-readable approval authority.
    pub approval_authority: Cow<'static, str>,
}

/// A file entry returned by a runtime adapter.
#[derive(Debug, Clone, Serialize)]
pub struct WorkspaceFile {
    /// Workspace-relative path.
    pub path: String,
    /// File size in bytes.
    pub size_bytes: u64,
    /// SHA-256 digest prefixed with `sha256:`.
    pub digest: String,
}

/// File content plus its authoritative digest.
#[derive(Debug, Clone, Serialize)]
pub struct FileSnapshot {
    /// Workspace-relative path.
    pub path: String,
    /// UTF-8 file content.
    pub content: String,
    /// SHA-256 digest of `content`.
    pub digest: String,
}

/// A validated, not-yet-applied proposal.
#[derive(Debug, Clone, Serialize)]
pub struct PatchProposal {
    /// Opaque proposal identity.
    pub proposal_id: String,
    /// Structured changes included in the proposal.
    pub changes: Vec<FileChange>,
    /// Authoritative unified diff generated by the adapter.
    pub unified_diff: String,
}

/// Result of an applied proposal.
#[derive(Debug, Clone, Serialize)]
pub struct AppliedChange {
    /// Opaque identity required for revert.
    pub change_id: String,
    /// Paths changed by the proposal.
    pub paths: Vec<String>,
}

/// Result of a check command.
#[derive(Debug, Clone, Serialize)]
pub struct CheckResult {
    /// Parsed command text.
    pub command: String,
    /// Process exit code, if the process started.
    pub exit_code: Option<i32>,
    /// Captured standard output.
    pub stdout: String,
    /// Captured standard error.
    pub stderr: String,
}

/// Result of a submitted agent turn.
#[derive(Debug, Clone, Serialize)]
pub struct TurnResult {
    /// Runtime-assigned turn identifier.
    pub turn_id: String,
    /// Whether the turn was accepted for execution.
    pub accepted: bool,
}

/// The runtime boundary used by the WebMCP transport.
#[async_trait]
pub trait RuntimeAdapter: Send + Sync {
    /// Return a page from the canonical execution projection.
    async fn explanation_get(
        &self,
        _scope: vtcode_memory::explanation::ExplanationScope,
        _offset: usize,
    ) -> Result<vtcode_memory::explanation::ExplanationPage> {
        Err(crate::WebmcpError::Unsupported("execution explanations".into()))
    }
    /// Return a redacted canonical evidence page.
    async fn explanation_evidence(
        &self,
        _reference: vtcode_memory::explanation::EvidenceRef,
        _offset: usize,
    ) -> Result<vtcode_memory::explanation::EvidencePage> {
        Err(crate::WebmcpError::Unsupported("execution evidence".into()))
    }
    /// Focus retained evidence through a typed UI channel; never submits input.
    async fn explanation_navigate(&self, _reference: vtcode_memory::explanation::EvidenceRef) -> Result<bool> {
        Err(crate::WebmcpError::Unsupported("execution navigation".into()))
    }
    /// Return current workspace and permission state.
    async fn status(&self) -> Result<RuntimeStatus>;

    /// List files visible to the session.
    async fn list_files(&self) -> Result<Vec<WorkspaceFile>>;

    /// Read one visible file.
    async fn read_file(&self, path: &str) -> Result<FileSnapshot>;

    /// Validate and stage a proposal without mutating the workspace.
    async fn propose_changes(&self, changes: Vec<FileChange>) -> Result<PatchProposal>;

    /// Apply a proposal through the runtime's approval authority.
    async fn apply_proposal(&self, proposal_id: &str) -> Result<AppliedChange>;

    /// Run a runtime-approved check command.
    async fn run_checks(&self, command: &str) -> Result<CheckResult>;

    /// Revert a still-current last change.
    async fn revert_last_change(&self, change_id: &str) -> Result<AppliedChange>;

    /// Submit a prompt and optional validated proposal to the active runtime.
    async fn request_turn(&self, prompt: &str, proposal_id: Option<&str>) -> Result<TurnResult>;

    /// Cancel a runtime request.
    ///
    /// The boolean reports whether an active operation was found and accepted
    /// for cancellation. Unknown or already-complete identifiers are not
    /// errors, which keeps reconnecting clients idempotent.
    async fn cancel(&self, _target_id: &str) -> Result<bool> {
        Ok(false)
    }
}
