//! openrouter_presets — provider preset definitions for openrouter.

use super::super::{ModelPreset, ReasoningEffortPreset};
use crate::config::models::Provider;
use crate::config::types::ReasoningEffortLevel;
pub(crate) fn openrouter_presets() -> Vec<ModelPreset> {
    vec![
        ModelPreset {
            id: "openrouter/meta/muse-glimmer-30b".to_string(),
            model: "meta/muse-glimmer-30b".to_string(),
            display_name: "Muse Glimmer 30B (OpenRouter)".to_string(),
            description: "Meta Muse Glimmer 30B reasoning model served through OpenRouter".to_string(),
            provider: Provider::OpenRouter,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::Low,
                    description: "Fast".to_string(),
                },
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::Medium,
                    description: "Balanced".to_string(),
                },
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::High,
                    description: "Deep".to_string(),
                },
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::XHigh,
                    description: "Maximum".to_string(),
                },
            ],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(131_072),
        },
        ModelPreset {
            id: "openrouter/deepseek-ai/DeepSeek-V4.1-Flash".to_string(),
            model: "deepseek-ai/DeepSeek-V4.1-Flash".to_string(),
            display_name: "DeepSeek V4.1 Flash (OpenRouter)".to_string(),
            description: "Latest DeepSeek flash model with improved reasoning and efficiency via OpenRouter"
                .to_string(),
            provider: Provider::OpenRouter,
            default_reasoning_effort: ReasoningEffortLevel::High,
            supported_reasoning_efforts: vec![
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::Low,
                    description: "Fast".to_string(),
                },
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::High,
                    description: "Balanced".to_string(),
                },
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::Max,
                    description: "Maximum thinking".to_string(),
                },
            ],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_000_000),
        },
        ModelPreset {
            id: "openrouter/moonshotai/kimi-k3".to_string(),
            model: "moonshotai/kimi-k3".to_string(),
            display_name: "Kimi K3 (OpenRouter)".to_string(),
            description: "Kimi K3 2.8T parameter flagship with 1M context, native vision, and always-on deep reasoning via OpenRouter".to_string(),
            provider: Provider::OpenRouter,
            default_reasoning_effort: ReasoningEffortLevel::Max,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Max,
                description: "Maximum (only supported level)".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_048_576),
        },

        ModelPreset {
            id: "openrouter/tencent/hy3-preview".to_string(),
            model: "tencent/hy3-preview".to_string(),
            display_name: "Hy3 Preview (OpenRouter)".to_string(),
            description: "Tencent Hy3 high-efficiency MoE model with configurable reasoning via OpenRouter".to_string(),
            provider: Provider::OpenRouter,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::Low,
                    description: "Fast".to_string(),
                },
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::Medium,
                    description: "Balanced".to_string(),
                },
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::High,
                    description: "Deep".to_string(),
                },
            ],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(262_144),
        },
        ModelPreset {
            id: "openrouter/x-ai/grok-4.6".to_string(),
            model: "x-ai/grok-4.6".to_string(),
            display_name: "Grok 4.6 (OpenRouter)".to_string(),
            description: "xAI Grok 4.6 flagship reasoning model for long-running agents via OpenRouter".to_string(),
            provider: Provider::OpenRouter,
            default_reasoning_effort: ReasoningEffortLevel::High,
            supported_reasoning_efforts: vec![
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::Low,
                    description: "Fast".to_string(),
                },
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::Medium,
                    description: "Balanced".to_string(),
                },
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::High,
                    description: "Deep (default)".to_string(),
                },
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::XHigh,
                    description: "Maximum depth".to_string(),
                },
            ],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(500_000),
        },
        ModelPreset {
            id: "openrouter/x-ai/grok-4.7".to_string(),
            model: "x-ai/grok-4.7".to_string(),
            display_name: "Grok 4.7 (OpenRouter)".to_string(),
            description: "xAI Grok 4.7 flagship reasoning model for long-running agents via OpenRouter".to_string(),
            provider: Provider::OpenRouter,
            default_reasoning_effort: ReasoningEffortLevel::High,
            supported_reasoning_efforts: vec![
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::Low,
                    description: "Fast".to_string(),
                },
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::Medium,
                    description: "Balanced".to_string(),
                },
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::High,
                    description: "Deep (default)".to_string(),
                },
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::XHigh,
                    description: "Maximum depth".to_string(),
                },
            ],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(500_000),
        },
        ModelPreset {
            id: "openrouter/xiaomi/mimo-v2.6-pro".to_string(),
            model: "xiaomi/mimo-v2.6-pro".to_string(),
            display_name: "MiMo-V2.6-Pro (OpenRouter)".to_string(),
            description: "Xiaomi MiMo-V2.6-Pro flagship agentic model for complex software engineering via OpenRouter".to_string(),
            provider: Provider::OpenRouter,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: true,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_048_576),
        },
        ModelPreset {
            id: "openrouter/xiaomi/mimo-v2.6-flash".to_string(),
            model: "xiaomi/mimo-v2.6-flash".to_string(),
            display_name: "MiMo-V2.6-Flash (OpenRouter)".to_string(),
            description: "Xiaomi MiMo-V2.6-Flash efficient high-volume agentic model via OpenRouter".to_string(),
            provider: Provider::OpenRouter,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_048_576),
        },
        ModelPreset {
            id: "openrouter/xiaomi/mimo-v2.6-pro-ultraspeed".to_string(),
            model: "xiaomi/mimo-v2.6-pro-ultraspeed".to_string(),
            display_name: "MiMo-V2.6-Pro-UltraSpeed (OpenRouter)".to_string(),
            description: "Xiaomi MiMo-V2.6-Pro-UltraSpeed fastest flagship variant via OpenRouter".to_string(),
            provider: Provider::OpenRouter,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_048_576),
        },
        ModelPreset {
            id: "openrouter/poolside/laguna-m.1:free".to_string(),
            model: "poolside/laguna-m.1:free".to_string(),
            display_name: "Laguna M.1 free (OpenRouter)".to_string(),
            description: "Poolside Laguna M.1 flagship free coding agent model via OpenRouter".to_string(),
            provider: Provider::OpenRouter,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(262_144),
        },
        ModelPreset {
            id: "openrouter/poolside/laguna-s-2.1:free".to_string(),
            model: "poolside/laguna-s-2.1:free".to_string(),
            display_name: "Laguna S 2.1 free (OpenRouter)".to_string(),
            description: "Poolside Laguna S 2.1 118B MoE free coding agent model with 256K context via OpenRouter".to_string(),
            provider: Provider::OpenRouter,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(262_144),
        },
        ModelPreset {
            id: "openrouter/google/gemini-3.5-flash-lite".to_string(),
            model: "google/gemini-3.5-flash-lite".to_string(),
            display_name: "Gemini 3.5 Flash Lite (OpenRouter)".to_string(),
            description: "Cost-optimized lightweight Gemini model for efficient inference via OpenRouter".to_string(),
            provider: Provider::OpenRouter,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_048_576),
        },
        ModelPreset {
            id: "openrouter/google/gemini-3.6-flash".to_string(),
            model: "google/gemini-3.6-flash".to_string(),
            display_name: "Gemini 3.6 Flash (OpenRouter)".to_string(),
            description: "Latest Gemini flash model with improved reasoning and efficiency via OpenRouter".to_string(),
            provider: Provider::OpenRouter,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![ReasoningEffortPreset {
                effort: ReasoningEffortLevel::Medium,
                description: "Balanced".to_string(),
            }],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_048_576),
        },
        ModelPreset {
            id: "openrouter/google/gemini-3.7-flash".to_string(),
            model: "google/gemini-3.7-flash".to_string(),
            display_name: "Gemini 3.7 Flash (OpenRouter)".to_string(),
            description: "Flash model with 1M context and tunable thinking levels via OpenRouter".to_string(),
            provider: Provider::OpenRouter,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::Low,
                    description: "Fast responses".to_string(),
                },
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::Medium,
                    description: "Balanced reasoning".to_string(),
                },
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::High,
                    description: "Deep reasoning".to_string(),
                },
            ],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_048_576),
        },
        ModelPreset {
            id: "openrouter/google/gemini-3.8-flash".to_string(),
            model: "google/gemini-3.8-flash".to_string(),
            display_name: "Gemini 3.8 Flash (OpenRouter)".to_string(),
            description: "Most intelligent Flash for long-horizon SWE, agents, and enterprise workflows via OpenRouter".to_string(),
            provider: Provider::OpenRouter,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: vec![
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::Low,
                    description: "Fast responses".to_string(),
                },
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::Medium,
                    description: "Balanced reasoning".to_string(),
                },
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::High,
                    description: "Deep reasoning".to_string(),
                },
            ],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_048_576),
        },

        ModelPreset {
            id: "openrouter/openai/gpt-6-astra".to_string(),
            model: "openai/gpt-6-astra".to_string(),
            display_name: "GPT-6 Astra (OpenRouter)".to_string(),
            description: "OpenAI's flagship model for demanding end-to-end work via OpenRouter".to_string(),
            provider: Provider::OpenRouter,
            default_reasoning_effort: ReasoningEffortLevel::High,
            supported_reasoning_efforts: vec![
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::Low,
                    description: "Fast".to_string(),
                },
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::Medium,
                    description: "Balanced".to_string(),
                },
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::High,
                    description: "Deep (default)".to_string(),
                },
                ReasoningEffortPreset {
                    effort: ReasoningEffortLevel::XHigh,
                    description: "Maximum depth".to_string(),
                },
            ],
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_050_000),
        },
    ]
}
