//! vercel_presets — provider preset definitions for the Vercel AI Gateway.

use super::super::{ModelPreset, ModelUpgrade};
use crate::config::constants::models::vercel as vercel_models;
use crate::config::models::Provider;
use crate::config::types::ReasoningEffortLevel;

pub(crate) fn vercel_presets() -> Vec<ModelPreset> {
    vec![
        ModelPreset {
            id: "vercel/anthropic/claude-sonnet-5".to_string(),
            model: vercel_models::ANTHROPIC_CLAUDE_SONNET_5.to_string(),
            display_name: "Claude Sonnet 5 (Vercel AI Gateway)".to_string(),
            description: "Anthropic Claude Sonnet 5 served through the Vercel AI Gateway with 1M context.".to_string(),
            provider: Provider::Vercel,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: Vec::new(),
            is_default: true,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_000_000),
        },
        ModelPreset {
            id: "vercel/anthropic/claude-opus-5".to_string(),
            model: vercel_models::ANTHROPIC_CLAUDE_OPUS_5.to_string(),
            display_name: "Claude Opus 5 (Vercel AI Gateway)".to_string(),
            description: "Anthropic Claude Opus 5 flagship model served through the Vercel AI Gateway.".to_string(),
            provider: Provider::Vercel,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: Vec::new(),
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_000_000),
        },
        ModelPreset {
            id: "vercel/anthropic/claude-haiku-4.5".to_string(),
            model: vercel_models::ANTHROPIC_CLAUDE_HAIKU_4_5.to_string(),
            display_name: "Claude Haiku 4.5 (Vercel AI Gateway)".to_string(),
            description: "Anthropic Claude Haiku 4.5 fast, cost-efficient model served through the Vercel AI Gateway."
                .to_string(),
            provider: Provider::Vercel,
            default_reasoning_effort: ReasoningEffortLevel::Low,
            supported_reasoning_efforts: Vec::new(),
            is_default: false,
            upgrade: Some(ModelUpgrade {
                id: "vercel/anthropic/claude-sonnet-5".to_string(),
                migration_config_key: String::new(),
                upgrade_copy: Some(
                    "Upgrade to Claude Sonnet 5 for stronger long-horizon coding performance.".to_string(),
                ),
                reasoning_effort_mapping: None,
                model_link: None,
            }),
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(200_000),
        },
        ModelPreset {
            id: "vercel/openai/gpt-5.6-sol".to_string(),
            model: vercel_models::OPENAI_GPT_5_6_SOL.to_string(),
            display_name: "GPT-5.6 Sol (Vercel AI Gateway)".to_string(),
            description: "OpenAI GPT-5.6 Sol flagship reasoning model served through the Vercel AI Gateway."
                .to_string(),
            provider: Provider::Vercel,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: Vec::new(),
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_050_000),
        },
        ModelPreset {
            id: "vercel/openai/gpt-6-astra".to_string(),
            model: vercel_models::OPENAI_GPT_6_ASTRA.to_string(),
            display_name: "GPT-6 Astra (Vercel AI Gateway)".to_string(),
            description: "OpenAI GPT-6 Astra flagship reasoning model served through the Vercel AI Gateway."
                .to_string(),
            provider: Provider::Vercel,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: Vec::new(),
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_050_000),
        },
        ModelPreset {
            id: "vercel/openai/gpt-5.6-luna".to_string(),
            model: vercel_models::OPENAI_GPT_5_6_LUNA.to_string(),
            display_name: "GPT-5.6 Luna (Vercel AI Gateway)".to_string(),
            description: "OpenAI GPT-5.6 Luna cost-efficient reasoning model served through the Vercel AI Gateway."
                .to_string(),
            provider: Provider::Vercel,
            default_reasoning_effort: ReasoningEffortLevel::Low,
            supported_reasoning_efforts: Vec::new(),
            is_default: false,
            upgrade: Some(ModelUpgrade {
                id: "vercel/openai/gpt-5.6-sol".to_string(),
                migration_config_key: String::new(),
                upgrade_copy: Some("Upgrade to GPT-5.6 Sol for stronger reasoning on complex tasks.".to_string()),
                reasoning_effort_mapping: None,
                model_link: None,
            }),
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_050_000),
        },
        ModelPreset {
            id: "vercel/openai/gpt-5.6-luna".to_string(),
            model: vercel_models::GOOGLE_GEMINI_3_8_FLASH.to_string(),
            display_name: "Gemini 3.8 Flash (Vercel AI Gateway)".to_string(),
            description: "Google Gemini 3.8 Flash fast, cost-efficient model served through the Vercel AI Gateway."
                .to_string(),
            provider: Provider::Vercel,
            default_reasoning_effort: ReasoningEffortLevel::Low,
            supported_reasoning_efforts: Vec::new(),
            is_default: false,
            upgrade: Some(ModelUpgrade {
                id: "vercel/google/gemini-3.1-pro-preview".to_string(),
                migration_config_key: String::new(),
                upgrade_copy: Some("Upgrade to Gemini 3.1 Pro Preview for maximum reasoning quality.".to_string()),
                reasoning_effort_mapping: None,
                model_link: None,
            }),
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_000_000),
        },
        ModelPreset {
            id: "vercel/deepseek/deepseek-v4.1-flash".to_string(),
            model: vercel_models::DEEPSEEK_FLASH.to_string(),
            display_name: "DeepSeek V4.1 Flash (Vercel AI Gateway)".to_string(),
            description: "DeepSeek V4.1 Flash latest flash model served through the Vercel AI Gateway.".to_string(),
            provider: Provider::Vercel,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: Vec::new(),
            is_default: false,
            upgrade: Some(ModelUpgrade {
                id: "vercel/deepseek/deepseek-flash".to_string(),
                migration_config_key: String::new(),
                upgrade_copy: Some("Upgrade to DeepSeek V4.1 Flash — V4 Flash is now retired.".to_string()),
                reasoning_effort_mapping: None,
                model_link: None,
            }),
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_000_000),
        },
        ModelPreset {
            id: "vercel/moonshotai/kimi-k3".to_string(),
            model: vercel_models::MOONSHOTAI_KIMI_K3.to_string(),
            display_name: "Kimi K3 (Vercel AI Gateway)".to_string(),
            description: "Moonshot AI Kimi K3 flagship reasoning model served through the Vercel AI Gateway."
                .to_string(),
            provider: Provider::Vercel,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: Vec::new(),
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(1_000_000),
        },
        ModelPreset {
            id: "vercel/minimax/minimax-m3".to_string(),
            model: vercel_models::MINIMAX_M3.to_string(),
            display_name: "MiniMax M3 (Vercel AI Gateway)".to_string(),
            description: "MiniMax M3 long-context reasoning model served through the Vercel AI Gateway.".to_string(),
            provider: Provider::Vercel,
            default_reasoning_effort: ReasoningEffortLevel::Medium,
            supported_reasoning_efforts: Vec::new(),
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(512_000),
        },
        ModelPreset {
            id: "vercel/spacexai/grok-4.7".to_string(),
            model: vercel_models::SPACEXAI_GROK_4_7.to_string(),
            display_name: "Grok 4.7 (Vercel AI Gateway)".to_string(),
            description:
                "xAI Grok 4.7 flagship reasoning model for long-running agents served through the Vercel AI Gateway."
                    .to_string(),
            provider: Provider::Vercel,
            default_reasoning_effort: ReasoningEffortLevel::High,
            supported_reasoning_efforts: Vec::new(),
            is_default: false,
            upgrade: None,
            show_in_picker: true,
            supported_in_api: true,
            context_window: Some(500_000),
        },
    ]
}
